@include('layouts.head')
@include('layouts.preloader')
@include('layouts.main_menu')
@include('layouts.navigation')
@include('service.service')
@include('layouts.contacts')
@include('layouts.footer')
